version: '3'
services:
    backend:
        build: 
            context: .
            dockerfile: Dockerfile-backend-app
        depends_on:
            - db
        environment:
            APP_ENV: ${APP_ENV}
            BACKEND_PORT_INNER: ${BACKEND_PORT_INNER}
            DJANGO_SETTINGS_MODULE: ratatatouille.settings.${APP_ENV}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_HOST_DEV: ${MYSQL_HOST_DEV}
            MYSQL_HOST_PROD: ${MYSQL_HOST_PROD}
            MYSQL_HOST_TEST: ${MYSQL_HOST_TEST}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_PORT: ${MYSQL_PORT_INNER}
            MYSQL_USER: ${MYSQL_USER}
        networks:
            - ratatatouille
        volumes:
            - ./backend-app:/backend-app
            - static_volume:/backend-app/static

    gateway:
        command: >
            sh -c "envsubst '$${BACKEND_PORT_INNER},$${GATEWAY_PORT_INNER}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"
        depends_on:
            - backend
        environment:
            BACKEND_PORT_INNER: ${BACKEND_PORT_INNER}
            GATEWAY_PORT_INNER: ${GATEWAY_PORT_INNER}
        image: nginx:1.13.0-alpine
        networks:
            - ratatatouille
        ports:
            - "${GATEWAY_PORT_OUTER}:${GATEWAY_PORT_INNER}"
        volumes:
            - ./gateway/config/nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
            - static_volume:/opt/services/backend-app/static

    db:
        image: mysql:8.0.12
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
        ports:
            - "${MYSQL_PORT_OUTER}:${MYSQL_PORT_INNER}"
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/mysql.cnf:/etc/mysql/conf.d/sql_mode.cnf:ro
        networks:
            - ratatatouille

    dbtest:
        image: mysql:8.0.12
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
        ports:
            - "${MYSQL_PORT_TEST_OUTER}:${MYSQL_PORT_TEST_INNER}"
        volumes:
            - ./dbtest/data:/var/lib/mysql
            - ./dbtest/mysql.cnf:/etc/mysql/conf.d/sql_mode.cnf:ro
        networks:
            - ratatatouille

networks:
    ratatatouille:
        driver: bridge

volumes:
    static_volume:
